### ISSUE TITLE
Route parameters instead of body in GET

### ISSUE THREAD

**Issue by eiktyrner** [hoodsy/3ree-auth-example#3]
Adding a body to a GET request is very weird and I think it breaks HTTP/1.1 spec
[Code](https://github.com/hoodsy/3ree-auth-example/blob/6059c5d452fc01b1e1b6c304aa886cca34076774/server/routes/users.js#l4)

Have you considered switching it to a route parameter? I'd do a PR on it but too busy right now. Just though I would let you know about it

**Comment by hoodsy** [comment]
@eiktyrner thanks for pointing this out, it does seem to be a bit strange. 

I definitely appreciate any and all contributions, but I will try to get to this ASAP!

**Comment by snobear** [comment]
+1.  One reason is if you use Postman for testing your API out; it doesn't support sending a body with a GET request.

**Comment by hoodsy** [comment]
@eiktyrner @snobear made this change - thanks for pointing this out.
