### ISSUE TITLE
Server Side Debugging

### ISSUE THREAD

**Issue by ajonesgh** [hoodsy/3ree-auth-example#7]
Is there a way to debug the server side code?

**Comment by hoodsy** [comment]
@Ad4mJ I would recommend using Postman to hit the API endpoints, if that's what you are referring to.

Or, what specifically are you trying to debug?

**Comment by Ad4mJ** [comment]
As the

**Comment by ajonesgh** [comment]
As in the server side api calls 

For example i would like to debug server/api/dashboards.js createDashboard method to see what is getting passed in.

**Comment by hoodsy** [comment]
@Ad4mJ you could use console.log statements, or the nicely maintained node-debugger.
